version: "3.9"

services:
  neo4j:
    image: neo4j:5.21
    container_name: neo4j
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_auth__enabled: "true"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/api/tags >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    command: ["/bin/sh","-lc","ollama pull llama3 && ollama pull mxbai-embed-large"]
    restart: "no"

  importer:
    build: .
    container_name: importer
    depends_on:
      neo4j:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully
    environment:
      NEO4J_URL: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASS: "password"
      OLLAMA_BASE_URL: "http://ollama:11434"
      PDF_PATH: "/data/paper.pdf"
      VEC_INDEX_NAME: "pdf_chunks_vec"
      KW_INDEX_NAME: "pdf_chunks_kw"
      NODE_LABEL: "Document"
      TEXT_PROP: "text"
      EMBED_PROP: "embedding"
      CHUNK_SIZE: "800"
      CHUNK_OVERLAP: "120"
      GRAPH_CHUNK_CAP: "200"
      GRAPH_BATCH_SIZE: "50"
    volumes:
      - ./data:/data
    command: ["python","-m","importer.main"]
    restart: "no"

  qa:
    build: .
    container_name: qa
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_healthy
      importer:
        condition: service_completed_successfully
    environment:
      NEO4J_URL: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASS: "password"
      OLLAMA_BASE_URL: "http://ollama:11434"
      OLLAMA_LLM_MODEL: "llama3"
      OLLAMA_EMBED_MODEL: "mxbai-embed-large"
      NODE_LABEL: "Document"
      TEXT_PROP: "text"
      EMBED_PROP: "embedding"
      VEC_INDEX_NAME: "pdf_chunks_vec"
      KW_INDEX_NAME: "pdf_chunks_kw"
    ports:
      - "8000:8000"
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
    restart: unless-stopped

volumes:
  neo4j-data:
  neo4j-logs:
  ollama: